#!/bin/bash
echo "================================================"
echo "CREATING IOS APP PROJECT - STEP BY STEP"
echo "================================================"
echo ""
echo "Since you need to run on your iPhone, follow these exact steps:"
echo ""
echo "1. Open Xcode"
echo "2. File → New → Project"
echo "3. Select 'iOS' tab at the top"
echo "4. Select 'App' template"
echo "5. Click 'Next'"
echo ""
echo "6. Fill in the form:"
echo "   Product Name: StudentStudyHaven"
echo "   Team: [Select your Apple ID]"
echo "   Organization Identifier: com.studentstudyhaven" 
echo "   Bundle Identifier: com.studentstudyhaven.app"
echo "   Interface: SwiftUI"
echo "   Language: Swift"
echo "   ☑️ Use Core Data: NO"
echo "   ☑️ Include Tests: NO"
echo ""
echo "7. Click 'Next'"
echo "8. Save location: Navigate to and select:"
echo "   /Users/benh/Documents/StudentStudyHaven/"
echo "9. ☑️ Create Git repository: NO"
echo "10. Click 'Create'"
echo ""
echo "================================================"
echo "THEN RUN THIS SCRIPT TO CONFIGURE THE PROJECT:"
echo "================================================"
echo ""
echo "chmod +x configure_ios_project.sh"
echo "./configure_ios_project.sh"
echo ""
echo "Ready? Open Xcode and create the project, then come back here."
